from django.urls import path
from .views import *

urlpatterns = [
    path('admin-login/',admin_login_api),
    path('add-category/',add_category),
    path('manage-category/',list_category),
    path('add-food-item/',add_food_item),
    path('foods/',list_foods),
    path('foods_search/',foods_search),
    path('random_foods/',random_foods),
    path('register/',register),
    path('login/',login),
    path('foods/<int:id>/',food_detail),
    path('add-cart/',add_to_cart),
    path('cart/<int:user_id>/',get_cart_item),
    path('cart/update-quantity/',update_cart_quantity),
    path('cart/delete_item/<int:order_id>/',delete_cart_item),
    path('place_order/',place_order),
    path('orders/<int:user_id>/',user_orders),
    path('orders/by_order_number/<str:order_number>/',order_by_order_number),
    path('order_address/<str:order_number>/',get_order_address),
    path('invoice/<str:order_number>/',get_invoice),
    path('user/<int:user_id>/',get_user_profile),
    path('user/update/<int:user_id>/',update_user_profile),
    path('change_password/<int:user_id>/',change_password),
    path('orders_not_confirmed/',orders_not_confirmed),
    path('orders_confirmed/',orders_confirmed),
    path('food_being_prepared/',food_being_prepared),
    path('food_pickup/',food_pickup),
    path('orders_delivered/',food_delivered),
    path('order_cancelled/',order_cancelled),
    path('all_orders/',all_orders),
    path('order-between-dates/',order_between_dates),
    path('view-order-details/<str:order_number>/',view_order_detail),
    path('update-order-status/',update_order_status),
    path('search-orders/',search_orders),
    path('category-detail/<int:id>/',category_detail),
    path('delete_food/<int:id>/',delete_food),
    path('edit-food/<int:id>/',edit_food),
    path('manage-users/',list_users),
    path('delete-user/<int:id>/',delete_user),
    path('dashboard-metrics/',dashboard_metrics),
]