# Generated by Django 5.2.6 on 2025-10-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0004_foodtracking_orderaddress_paymentdetail_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
