# Generated by Django 5.2.6 on 2025-10-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0005_alter_paymentdetail_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
